from settings.defaults import *

# MPD
###
MPD_HOST = '{{ MPD_HOST }}'
MPD_PORT = {{ MPD_PORT }}

# Uploads
###
UPLOADS_FOLDER = '{{ UPLOADS_FOLDER }}'

# Global Settings
###
PRODUCTION = {{ PRODUCTION }} 
DEVELOPMENT = not PRODUCTION

DEBUG = not PRODUCTION
TESTING = DEBUG
ASSETS_DEBUG = DEBUG
SECRET_KEY = """{{ SECRET_KEY }}"""

# MongoDB
###
MONGODB_DATABASE = '{{ MONGODB_DATABASE }}'
MONGODB_HOST = '{{ MONGODB_HOST }}'
MONGODB_PORT = {{ MONGODB_PORT }}
MONGODB_USERNAME = '{{ MONGODB_USERNAME }}'
MONGODB_PASSWORD = '{{ MONGODB_PASSWORD }}'

# Cache
###
CACHE_TYPE = 'null'
CACHE_DEFAULT_TIMEOUT = 300
#CACHE_TYPE = 'memcached'
#CACHE_MEMCACHED_SERVERS = [os.environ.get('MEMCACHE_USERNAME')+':'+os.environ.get('MEMCACHE_PASSWORD')+'@'+os.environ.get('MEMCACHE_SERVERS'),]

